### PR TITLE
Add mocha test framework and CI GitHub Action

### LINKED ISSUE #30: Add integration tests and run them from Github action

### PR DESCRIPTION
**Pull request by MantisClone**
Closes #30

Changes:

- Add chai and mocah dev dependencies
- Add initial test.js file
- Update package.json so `npm test` runs the mocha tests
- Update author
- Add Node.JS CI Github action

### CODE REVIEW

**Comment by MantisClone** [comment]
I don't know why Node.js 14 fails and Node.js 18 gets cancelled. I'm going to leave them in there for now.

**Comment by MantisClone** [comment]
I updated the repo settings so that PRs are required to merge changes into main. I also changed it so that the `build (16.x)` check is required to merge.

**Comment by MantisClone** [comment]
The test is failing because I still need to add `PRIVATE_KEY` and `TEST_PRIVATE_KEY` as repository secrets.

**Comment by MantisClone** [comment]
When it passes it should look like this:

```
david@david-Inspiron-5502:~/projects/arweave-upload$ npm test

> arweave-upload@1.0.0 test
> mocha

Alice address: 0x519145B771a6e450461af89980e5C17Ff6Fd8A92


  DBS Arweave Upload
    getQuote
quote = {"quoteId":"5cc8009b0f0b2b323e78c0e1137bbee1","chainId":80001,"tokenAddress":"0x0000000000000000000000000000000000001010","tokenAmount":"40725319203292","approveAddress":"0x7eB023BFbAeE228de6DC5B92D0BeEB1eDb1Fd567"}
      ✔ Should return quote ID (496ms)


  1 passing (499ms)
```

**Review by corrie-sloot — APPROVED** [review]

**Comment by MantisClone** [comment]
Yay! The test passed so I'm merging.

**Pull request merged**
